version: '3.1'

networks:
  backend:
    labels:
      description: 'backend services network'

  frontend:
    labels:
      description: 'frontend server network'

services:
  backend:
    build:
      context: ./backend
      args:
        - profile=dev
    image: school-register-backend:1.0.0
    container_name: school-register-backend

    ports:
      - 3000:${PORT:-3000}

    environment:
      - PORT=3000
      - DB_HOST=mongodb
      - DB_PORT=27017
      - DB_USERNAME=school_register
      - DB_PASSWORD=school_register
      - DB_NAME=school_register
      - DB_ARGS=ssl=false
      - JWT_SECRET=secret
      - JWT_EXPIRATION_TIME=1h

    hostname: backend

    networks:
      - backend
      - frontend
    depends_on:
      - mongodb
    restart: always

  mongodb:
    image: mongo:5.0.4
    container_name: school-register-mongodb

    ports:
      - 3001:27017

    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin

      MONGO_INITDB_DATABASE: school_register
      MONGO_INITDB_USER: school_register
      MONGO_INITDB_PASSWORD: school_register

    volumes:
      - ./backend/mongo-data:/data/db
      - ./backend/mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh:ro

    hostname: mongodb

    networks:
      - backend
    restart: always

  mongo-express:
    image: mongo-express:1.0.0-alpha.4
    container_name: school-register-mongo-express

    ports:
      - 3002:8081

    environment:
      ME_CONFIG_MONGODB_ENABLE_ADMIN: 'true'
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin

      #ME_CONFIG_SITE_SSL_ENABLED: 'true'
      #ME_CONFIG_SITE_SSL_CRT_PATH:
      #ME_CONFIG_SITE_SSL_KEY_PATH:

      #ME_CONFIG_MONGODB_SSLVALIDATE: true
      #ME_CONFIG_MONGODB_CA_FILE:

      ME_CONFIG_MONGODB_AUTH_DATABASE: admin
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
      ME_CONFIG_MONGODB_URL: mongodb://admin:admin@mongodb:27017?ssl=false

    hostname: mongo-express

    networks:
      - backend
    depends_on:
      - mongodb
    restart: always

  frontend:
    build:
      context: ./frontend
      args:
        - backend_url=http://127.0.0.1:3000
        - profile=dev
    image: school-register-frontend:1.0.0
    container_name: school-register-frontend

    ports:
      - 3005:${PORT:-3000}

    environment:
      - PORT=3000

    hostname: frontend

    networks:
      - frontend
    restart: always
