version: '3.1'

networks:
  backend:
    labels:
      description: 'backend services network'

services:
  mongo:
    image: mongo:4.4.11-rc0-focal
    container_name: mongo
    ports:
      - 3001:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: 'school_register'
    volumes:
      - ./backend/mongo-data:/data/db
    hostname: mongodb
    networks:
      - backend
    restart: always

  mongo-express:
    image: mongo-express:1.0.0-alpha.4
    container_name: mongo-express
    ports:
      - 3002:8081
    environment:
      ME_CONFIG_MONGODB_ENABLE_ADMIN: 'true'
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin

      #ME_CONFIG_SITE_SSL_ENABLED: 'true'
      #ME_CONFIG_SITE_SSL_CRT_PATH:
      #ME_CONFIG_SITE_SSL_KEY_PATH:

      #ME_CONFIG_MONGODB_SSLVALIDATE: true
      #ME_CONFIG_MONGODB_CA_FILE:

      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
      ME_CONFIG_MONGODB_URL: mongodb://admin:admin@mongo:27017?ssl=false
    hostname: mongo-express
    networks:
      - backend
    depends_on:
      - mongo
    restart: always
