version: '3.1'

services:
  backend:
    build:
      args:
        - profile=prod

    ports:
      - 80:${SERVER_PORT:-3000}

  mongo-express:
    entrypoint: ['echo', 'mongo-express is disabled in prod environment']

    restart: 'no'

  frontend:
    build:
      args:
        - backend_url=http://127.0.0.1:3000
        - profile=prod

    ports:
      - 3005:${SERVER_PORT:-80}

    environment:
      - SERVER_PORT=80
