name: Heroku CD deploy React.js container

on:
  push:
    branches: [main]
    paths: ['frontend/**']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build, push and release a Docker React.js container to Heroku
        uses: gonuit/heroku-docker-deploy@v1.3.3
        with:
          email: ${{ secrets.HEROKU_EMAIL }}
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_REACTJS_APP_NAME }}
          dockerfile_directory: ./frontend
          dockerfile_name: Dockerfile
          docker_options: --build-arg backend_url=https://school-register-api.herokuapp.com --build-arg profile=prod

          process_type: web
